In [1008]:
import pandas as pd

In [1009]:
df = pd.read_csv('data.csv')
df

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
..        ...    ...       ...       ...
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

[169 rows x 4 columns]

In [1010]:
df.sort_values(by=["Duration", "Calories"] , ascending=True , inplace=True)
df

     Duration  Pulse  Maxpulse  Calories
93         15     80       100      50.5
112        15    124       139     124.2
89         20     83       107      50.3
100        20     95       112      77.7
68         20    106       136     110.4
..        ...    ...       ...       ...
65        180     90       130     800.4
60        210    108       160    1376.0
109       210    137       184    1860.4
79        270    100       131    1729.0
69        300    108       143    1500.2

[169 rows x 4 columns]

In [1011]:
df.head(0)
df.tail(10)

     Duration  Pulse  Maxpulse  Calories
70        150     97       129    1115.0
62        160    109       135     853.0
61        160    110       137    1034.4
90        180    101       127     600.1
106       180     90       120     800.3
65        180     90       130     800.4
60        210    108       160    1376.0
109       210    137       184    1860.4
79        270    100       131    1729.0
69        300    108       143    1500.2

In [1012]:
df.dropna(axis = 0 , how = 'any' , inplace = True)
df

     Duration  Pulse  Maxpulse  Calories
93         15     80       100      50.5
112        15    124       139     124.2
89         20     83       107      50.3
100        20     95       112      77.7
68         20    106       136     110.4
..        ...    ...       ...       ...
65        180     90       130     800.4
60        210    108       160    1376.0
109       210    137       184    1860.4
79        270    100       131    1729.0
69        300    108       143    1500.2

[164 rows x 4 columns]

In [1013]:
df.loc[10][ 'Duration'] = 45
df

     Duration  Pulse  Maxpulse  Calories
93         15     80       100      50.5
112        15    124       139     124.2
89         20     83       107      50.3
100        20     95       112      77.7
68         20    106       136     110.4
..        ...    ...       ...       ...
65        180     90       130     800.4
60        210    108       160    1376.0
109       210    137       184    1860.4
79        270    100       131    1729.0
69        300    108       143    1500.2

[164 rows x 4 columns]

In [1014]:
df

     Duration  Pulse  Maxpulse  Calories
93         15     80       100      50.5
112        15    124       139     124.2
89         20     83       107      50.3
100        20     95       112      77.7
68         20    106       136     110.4
..        ...    ...       ...       ...
65        180     90       130     800.4
60        210    108       160    1376.0
109       210    137       184    1860.4
79        270    100       131    1729.0
69        300    108       143    1500.2

[164 rows x 4 columns]

In [1015]:
df.loc[2, 'Duration'] = 452

In [1016]:
df.drop_duplicates(inplace = True)

In [1017]:
df.shape

(157, 4)

In [1018]:
df.columns

Index(['Duration', 'Pulse', 'Maxpulse', 'Calories'], dtype='object')

In [1019]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 157 entries, 93 to 69
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Duration  157 non-null    int64
 1   Pulse     157 non-null    int64
 2   Maxpulse  157 non-null    int64
 3   Calories  157 non-null    float64
dtypes: float64(1), int64(3)
memory usage: 6.1 KB

In [1020]:
df.describe()

         Duration       Pulse    Maxpulse     Calories
count  157.000000  157.000000  157.000000   157.000000
mean    67.019108  107.942675  134.509554   379.414650
std     53.596842   14.845029   16.607311   271.342426
min     15.000000   80.000000  100.000000    50.300000
25%     45.000000  100.000000  124.000000   251.000000
50%     60.000000  106.000000  131.000000   320.400000
75%     60.000000  112.000000  143.000000   390.000000
max    452.000000  159.000000  184.000000  1860.400000

In [1021]:
df.value_counts()

Duration  Pulse  Maxpulse  Calories
15        80     100       50.5        1
          124    139       124.2       1
20        83     107       50.3        1
          95     112       77.7        1
          106    136       110.4       1
                                      ..
210       108    160       1376.0      1
          137    184       1860.4      1
270       100    131       1729.0      1
300       108    143       1500.2      1
452       103    135       340.0       1
Name: count, Length: 157, dtype: int64

In [1022]:
df['Calories'].mean()

np.float64(379.41464968152866)

Fazer a mudança do codigo da aula 2 sobre eda

In [1023]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
import matplotlib.pyplot as plt
import seaborn as sns

In [1024]:
df['Calories'] = df['Calories'].fillna(df['Calories'].median())

In [1025]:
df = df.dropna(subset=['Calories','Duration'])

In [1026]:
df = pd.get_dummies(df, columns=['Duration'],drop_first=True,dtype=int)
df = pd.get_dummies(df, columns=["Pulse"], drop_first=True,dtype=int)

In [1027]:
df['Calories'].describe()

count     157.000000
mean      379.414650
std       271.342426
min        50.300000
25%       251.000000
50%       320.400000
75%       390.000000
max      1860.400000
Name: Calories, dtype: float64

In [1028]:
bins = [0,12,18,50,100]
labels = ['Calories','Duration','Pulse','Maxpulse']
df['faixaEtaria'] = pd.cut(x=df['Calories'], bins=bins, labels=labels)
df = pd.get_dummies(df, columns=['faixaEtaria'], drop_first=True,dtype=int)

In [1029]:
bins = [0,7.91,14.54,31,512]
labels = ['Calories','Duration','Pulse','Maxpulse']
df['faixaTarifas'] = pd.cut(x=df['Calories'], bins=bins, labels=labels)
df = pd.get_dummies(df, columns=['faixaTarifas'], drop_first=True,dtype=int)

In [1030]:
df.columns

Index(['Maxpulse', 'Calories', 'Duration_20', 'Duration_25', 'Duration_30',
       'Duration_45', 'Duration_60', 'Duration_75', 'Duration_80',
       'Duration_90', 'Duration_120', 'Duration_150', 'Duration_160',
       'Duration_180', 'Duration_210', 'Duration_270', 'Duration_300',
       'Duration_452', 'Pulse_83', 'Pulse_85', 'Pulse_90', 'Pulse_92',
       'Pulse_93', 'Pulse_95', 'Pulse_97', 'Pulse_98', 'Pulse_99', 'Pulse_100',
       'Pulse_101', 'Pulse_102', 'Pulse_103', 'Pulse_104', 'Pulse_105',
       'Pulse_106', 'Pulse_107', 'Pulse_108', 'Pulse_109', 'Pulse_110',
       'Pulse_111', 'Pulse_112', 'Pulse_113', 'Pulse_114', 'Pulse_115',
       'Pulse_116', 'Pulse_117', 'Pulse_118', 'Pulse_119', 'Pulse_120',
       'Pulse_121', 'Pulse_122', 'Pulse_123', 'Pulse_124', 'Pulse_125',
       'Pulse_129', 'Pulse_130', 'Pulse_136', 'Pulse_137', 'Pulse_141',
       'Pulse_149', 'Pulse_150', 'Pulse_151', 'Pulse_152', 'Pulse_153',
       'Pulse_159', 'faixaEtaria_Duration', 'faixaEtaria_Pulse',
       'faixaEtaria_Maxpulse', 'faixaTarifas_Duration', 'faixaTarifas_Pulse',
       'faixaTarifas_Maxpulse'],
      dtype='object')

In [1031]:
X = df[['Maxpulse']]
y = df['Calories']

In [1032]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [1033]:
model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [1034]:
y_pred = model.predict(X_test)
y_pred

array([417.8156837 , 524.17851579, 340.79432254, 340.79432254,
       355.465058  , 293.11443229, 373.80347732, 348.12969027,
       377.47116119, 337.12663867, 362.80042573, 399.47726438,
       351.79737413, 329.79127094, 322.45590321, 322.45590321,
       399.47726438, 388.47421278, 362.80042573, 359.13274186,
       388.47421278, 348.12969027, 322.45590321, 513.17546419,
       381.13884505, 414.14799984, 388.47421278, 414.14799984,
       377.47116119, 351.79737413, 348.12969027, 344.4620064 ])

In [1035]:
ErroQuadraticoMedio = mean_squared_error(y_pred,y_test)
r2 = r2_score(y_pred,y_test)

print(f"Erro Quadrático Médio: {ErroQuadraticoMedio}")
print(f"Coeficiente de Determinação (R²): {r2}")

Erro Quadrático Médio: 84894.54522121651
Coeficiente de Determinação (R²): -35.89297361615601