In [140]:
import pandas as pd

In [141]:
df = pd.read_csv('data.csv')
df

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
2         60  '2020/12/03'    103       135     340.0
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       136     374.0
7        450  '2020/12/08'    104       134     253.3
8         30  '2020/12/09'    109       133     195.1
9         60  '2020/12/10'     98       124     269.0
10        60  '2020/12/11'    103       147     329.3
11        60  '2020/12/12'    100       120     250.7
12        60  '2020/12/12'    100       120     250.7
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       132     379.3
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
17        60  '2020/12/17'    100       120     300.0
18        45  '2020/12/18'     90       112       NaN
19        60  '2020/12/19'    103       123     323.0
20        45  '2020/12/20'     97       125     243.0
21        60  '2020/12/21'    108       131     364.2
22        45           NaN    100       119     282.0
23        60  '2020/12/23'    130       101     300.0
24        45  '2020/12/24'    105       132     246.0
25        60  '2020/12/25'    102       126     334.5
26        60      20201226    100       120     250.0
27        60  '2020/12/27'     92       118     241.0
28        60  '2020/12/28'    103       132       NaN
29        60  '2020/12/29'    100       132     280.0
30        60  '2020/12/30'    102       129     380.3
31        60  '2020/12/31'     92       115     243.0

In [142]:
# from google.colab import drive
# drive.mount('/content/drive')

In [143]:
df.sort_values(by=["Duration", "Calories"] , ascending=True , inplace=True)
df

    Duration          Date  Pulse  Maxpulse  Calories
8         30  '2020/12/09'    109       133     195.1
20        45  '2020/12/20'     97       125     243.0
24        45  '2020/12/24'    105       132     246.0
22        45           NaN    100       119     282.0
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
18        45  '2020/12/18'     90       112       NaN
16        60  '2020/12/16'     98       120     215.2
27        60  '2020/12/27'     92       118     241.0
31        60  '2020/12/31'     92       115     243.0
26        60      20201226    100       120     250.0
11        60  '2020/12/12'    100       120     250.7
12        60  '2020/12/12'    100       120     250.7
9         60  '2020/12/10'     98       124     269.0
15        60  '2020/12/15'     98       123     275.0
29        60  '2020/12/29'    100       132     280.0
5         60  '2020/12/06'    102       127     300.0
17        60  '2020/12/17'    100       120     300.0
23        60  '2020/12/23'    130       101     300.0
19        60  '2020/12/19'    103       123     323.0
10        60  '2020/12/11'    103       147     329.3
25        60  '2020/12/25'    102       126     334.5
2         60  '2020/12/03'    103       135     340.0
13        60  '2020/12/13'    106       128     345.3
21        60  '2020/12/21'    108       131     364.2
6         60  '2020/12/07'    110       136     374.0
14        60  '2020/12/14'    104       132     379.3
30        60  '2020/12/30'    102       129     380.3
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
28        60  '2020/12/28'    103       132       NaN
7        450  '2020/12/08'    104       134     253.3

In [144]:
df.head(0)
df.tail(10)

    Duration          Date  Pulse  Maxpulse  Calories
2         60  '2020/12/03'    103       135     340.0
13        60  '2020/12/13'    106       128     345.3
21        60  '2020/12/21'    108       131     364.2
6         60  '2020/12/07'    110       136     374.0
14        60  '2020/12/14'    104       132     379.3
30        60  '2020/12/30'    102       129     380.3
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
28        60  '2020/12/28'    103       132       NaN
7        450  '2020/12/08'    104       134     253.3

In [145]:
df.dropna(axis = 0 , how = 'any' , inplace = True)
df

    Duration          Date  Pulse  Maxpulse  Calories
8         30  '2020/12/09'    109       133     195.1
20        45  '2020/12/20'     97       125     243.0
24        45  '2020/12/24'    105       132     246.0
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
16        60  '2020/12/16'     98       120     215.2
27        60  '2020/12/27'     92       118     241.0
31        60  '2020/12/31'     92       115     243.0
26        60      20201226    100       120     250.0
11        60  '2020/12/12'    100       120     250.7
12        60  '2020/12/12'    100       120     250.7
9         60  '2020/12/10'     98       124     269.0
15        60  '2020/12/15'     98       123     275.0
29        60  '2020/12/29'    100       132     280.0
5         60  '2020/12/06'    102       127     300.0
17        60  '2020/12/17'    100       120     300.0
23        60  '2020/12/23'    130       101     300.0
19        60  '2020/12/19'    103       123     323.0
10        60  '2020/12/11'    103       147     329.3
25        60  '2020/12/25'    102       126     334.5
2         60  '2020/12/03'    103       135     340.0
13        60  '2020/12/13'    106       128     345.3
21        60  '2020/12/21'    108       131     364.2
6         60  '2020/12/07'    110       136     374.0
14        60  '2020/12/14'    104       132     379.3
30        60  '2020/12/30'    102       129     380.3
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
7        450  '2020/12/08'    104       134     253.3

In [146]:
df.loc[10][ 'Duration'] = 45
df

<ipython-input-146-c0900a5e8d50>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.loc[10][ 'Duration'] = 45

    Duration          Date  Pulse  Maxpulse  Calories
8         30  '2020/12/09'    109       133     195.1
20        45  '2020/12/20'     97       125     243.0
24        45  '2020/12/24'    105       132     246.0
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
16        60  '2020/12/16'     98       120     215.2
27        60  '2020/12/27'     92       118     241.0
31        60  '2020/12/31'     92       115     243.0
26        60      20201226    100       120     250.0
11        60  '2020/12/12'    100       120     250.7
12        60  '2020/12/12'    100       120     250.7
9         60  '2020/12/10'     98       124     269.0
15        60  '2020/12/15'     98       123     275.0
29        60  '2020/12/29'    100       132     280.0
5         60  '2020/12/06'    102       127     300.0
17        60  '2020/12/17'    100       120     300.0
23        60  '2020/12/23'    130       101     300.0
19        60  '2020/12/19'    103       123     323.0
10        60  '2020/12/11'    103       147     329.3
25        60  '2020/12/25'    102       126     334.5
2         60  '2020/12/03'    103       135     340.0
13        60  '2020/12/13'    106       128     345.3
21        60  '2020/12/21'    108       131     364.2
6         60  '2020/12/07'    110       136     374.0
14        60  '2020/12/14'    104       132     379.3
30        60  '2020/12/30'    102       129     380.3
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
7        450  '2020/12/08'    104       134     253.3

In [147]:
df

    Duration          Date  Pulse  Maxpulse  Calories
8         30  '2020/12/09'    109       133     195.1
20        45  '2020/12/20'     97       125     243.0
24        45  '2020/12/24'    105       132     246.0
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
16        60  '2020/12/16'     98       120     215.2
27        60  '2020/12/27'     92       118     241.0
31        60  '2020/12/31'     92       115     243.0
26        60      20201226    100       120     250.0
11        60  '2020/12/12'    100       120     250.7
12        60  '2020/12/12'    100       120     250.7
9         60  '2020/12/10'     98       124     269.0
15        60  '2020/12/15'     98       123     275.0
29        60  '2020/12/29'    100       132     280.0
5         60  '2020/12/06'    102       127     300.0
17        60  '2020/12/17'    100       120     300.0
23        60  '2020/12/23'    130       101     300.0
19        60  '2020/12/19'    103       123     323.0
10        60  '2020/12/11'    103       147     329.3
25        60  '2020/12/25'    102       126     334.5
2         60  '2020/12/03'    103       135     340.0
13        60  '2020/12/13'    106       128     345.3
21        60  '2020/12/21'    108       131     364.2
6         60  '2020/12/07'    110       136     374.0
14        60  '2020/12/14'    104       132     379.3
30        60  '2020/12/30'    102       129     380.3
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
7        450  '2020/12/08'    104       134     253.3

In [148]:
df.loc[2, 'Duration'] = 452

In [149]:
df.drop_duplicates(inplace = True)

In [150]:
df.shape

(28, 5)

In [151]:
df.columns

Index(['Duration', 'Date', 'Pulse', 'Maxpulse', 'Calories'], dtype='object')

In [152]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 28 entries, 8 to 7
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Duration  28 non-null     int64
 1   Date      28 non-null     object
 2   Pulse     28 non-null     int64
 3   Maxpulse  28 non-null     int64
 4   Calories  28 non-null     float64
dtypes: float64(1), int64(3), object(1)
memory usage: 1.3+ KB

In [153]:
df.describe()

         Duration       Pulse    Maxpulse    Calories
count   28.000000   28.000000   28.000000   28.000000
mean    84.714286  104.250000  129.607143  307.417857
std    103.720014    7.886345   13.273028   67.412594
min     30.000000   92.000000  101.000000  195.100000
25%     60.000000  100.000000  122.250000  250.525000
50%     60.000000  103.000000  128.500000  300.000000
75%     60.000000  108.250000  133.250000  350.025000
max    452.000000  130.000000  175.000000  479.000000

In [154]:
df.value_counts()

Duration  Date          Pulse  Maxpulse  Calories
30        '2020/12/09'  109    133       195.1       1
45        '2020/12/04'  109    175       282.4       1
          '2020/12/05'  117    148       406.0       1
          '2020/12/20'  97     125       243.0       1
          '2020/12/24'  105    132       246.0       1
60        '2020/12/01'  110    130       409.1       1
          '2020/12/02'  117    145       479.0       1
          '2020/12/06'  102    127       300.0       1
          '2020/12/07'  110    136       374.0       1
          '2020/12/10'  98     124       269.0       1
          '2020/12/11'  103    147       329.3       1
          '2020/12/12'  100    120       250.7       1
          '2020/12/13'  106    128       345.3       1
          '2020/12/14'  104    132       379.3       1
          '2020/12/15'  98     123       275.0       1
          '2020/12/16'  98     120       215.2       1
          '2020/12/17'  100    120       300.0       1
          '2020/12/19'  103    123       323.0       1
          '2020/12/21'  108    131       364.2       1
          '2020/12/23'  130    101       300.0       1
          '2020/12/25'  102    126       334.5       1
          '2020/12/27'  92     118       241.0       1
          '2020/12/29'  100    132       280.0       1
          '2020/12/30'  102    129       380.3       1
          '2020/12/31'  92     115       243.0       1
          20201226      100    120       250.0       1
450       '2020/12/08'  104    134       253.3       1
452       '2020/12/03'  103    135       340.0       1
Name: count, dtype: int64

In [161]:
df['Calories'].mean()

np.float64(307.41785714285714)