In [53]:
import pandas as pd
df = pd.read_csv('https://www.w3schools.com/python/pandas/data.csv')

In [54]:
df.sort_values(by=["Duration", "Calories"] , ascending=True , inplace=True)
df

     Duration  Pulse  Maxpulse  Calories
93         15     80       100      50.5
112        15    124       139     124.2
89         20     83       107      50.3
100        20     95       112      77.7
68         20    106       136     110.4
..        ...    ...       ...       ...
65        180     90       130     800.4
60        210    108       160    1376.0
109       210    137       184    1860.4
79        270    100       131    1729.0
69        300    108       143    1500.2

[169 rows x 4 columns]

In [55]:
df.head(0)
df.tail(10)

     Duration  Pulse  Maxpulse  Calories
70        150     97       129    1115.0
62        160    109       135     853.0
61        160    110       137    1034.4
90        180    101       127     600.1
106       180     90       120     800.3
65        180     90       130     800.4
60        210    108       160    1376.0
109       210    137       184    1860.4
79        270    100       131    1729.0
69        300    108       143    1500.2

In [56]:
df.dropna(axis = 0 , how = 'any' , inplace = True)
df

     Duration  Pulse  Maxpulse  Calories
93         15     80       100      50.5
112        15    124       139     124.2
89         20     83       107      50.3
100        20     95       112      77.7
68         20    106       136     110.4
..        ...    ...       ...       ...
65        180     90       130     800.4
60        210    108       160    1376.0
109       210    137       184    1860.4
79        270    100       131    1729.0
69        300    108       143    1500.2

[164 rows x 4 columns]

In [57]:
df.loc[7][ 'Duration'] = 45
df

<ipython-input-57-6aebcbd013ce>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.loc[7][ 'Duration'] = 45

     Duration  Pulse  Maxpulse  Calories
93         15     80       100      50.5
112        15    124       139     124.2
89         20     83       107      50.3
100        20     95       112      77.7
68         20    106       136     110.4
..        ...    ...       ...       ...
65        180     90       130     800.4
60        210    108       160    1376.0
109       210    137       184    1860.4
79        270    100       131    1729.0
69        300    108       143    1500.2

[164 rows x 4 columns]

In [58]:
df

     Duration  Pulse  Maxpulse  Calories
93         15     80       100      50.5
112        15    124       139     124.2
89         20     83       107      50.3
100        20     95       112      77.7
68         20    106       136     110.4
..        ...    ...       ...       ...
65        180     90       130     800.4
60        210    108       160    1376.0
109       210    137       184    1860.4
79        270    100       131    1729.0
69        300    108       143    1500.2

[164 rows x 4 columns]

In [59]:
df.loc[2, 'Duration'] = 45
df

     Duration  Pulse  Maxpulse  Calories
93         15     80       100      50.5
112        15    124       139     124.2
89         20     83       107      50.3
100        20     95       112      77.7
68         20    106       136     110.4
..        ...    ...       ...       ...
65        180     90       130     800.4
60        210    108       160    1376.0
109       210    137       184    1860.4
79        270    100       131    1729.0
69        300    108       143    1500.2

[164 rows x 4 columns]

In [60]:
df.drop_duplicates(inplace = True)
df

     Duration  Pulse  Maxpulse  Calories
93         15     80       100      50.5
112        15    124       139     124.2
89         20     83       107      50.3
100        20     95       112      77.7
68         20    106       136     110.4
..        ...    ...       ...       ...
65        180     90       130     800.4
60        210    108       160    1376.0
109       210    137       184    1860.4
79        270    100       131    1729.0
69        300    108       143    1500.2

[157 rows x 4 columns]

In [61]:
df.shape

(157, 4)

In [62]:
df.columns

Index(['Duration', 'Pulse', 'Maxpulse', 'Calories'], dtype='object')