In [ ]:
df = pd.read_csv('data.csv')
df

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
2         60  '2020/12/03'    103       135     340.0
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       136     374.0
7        450  '2020/12/08'    104       134     253.3
8         30  '2020/12/09'    109       133     195.1
9         60  '2020/12/10'     98       124     269.0
10        60  '2020/12/11'    103       147     329.3
11        60  '2020/12/12'    100       120     250.7
12        60  '2020/12/12'    100       120     250.7
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       132     379.3
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
17        60  '2020/12/17'    100       120     300.0
18        45  '2020/12/18'     90       112       NaN
19        60  '2020/12/19'    103       123     323.0
20        45  '2020/12/20'     97       125     243.0
21        60  '2020/12/21'    108       131     364.2
22        45           NaN    100       119     282.0
23        60  '2020/12/23'    130       101     300.0
24        45  '2020/12/24'    105       132     246.0
25        60  '2020/12/25'    102       126     334.5
26        60      20201226    100       120     250.0
27        60  '2020/12/27'     92       118     241.0
28        60  '2020/12/28'    103       132       NaN
29        60  '2020/12/29'    100       132     280.0
30        60  '2020/12/30'    102       129     380.3
31        60  '2020/12/31'     92       115     243.0

In [ ]:
df.sort_values(by=["Duration", "Calories"], ascending=False, inplace=False, ignore_index=True)

    Duration          Date  Pulse  Maxpulse  Calories
0        450  '2020/12/08'    104       134     253.3
1         60  '2020/12/02'    117       145     479.0
2         60  '2020/12/01'    110       130     409.1
3         60  '2020/12/30'    102       129     380.3
4         60  '2020/12/14'    104       132     379.3
5         60  '2020/12/07'    110       136     374.0
6         60  '2020/12/21'    108       131     364.2
7         60  '2020/12/13'    106       128     345.3
8         60  '2020/12/03'    103       135     340.0
9         60  '2020/12/25'    102       126     334.5
10        60  '2020/12/11'    103       147     329.3
11        60  '2020/12/19'    103       123     323.0
12        60  '2020/12/06'    102       127     300.0
13        60  '2020/12/17'    100       120     300.0
14        60  '2020/12/23'    130       101     300.0
15        60  '2020/12/29'    100       132     280.0
16        60  '2020/12/15'     98       123     275.0
17        60  '2020/12/10'     98       124     269.0
18        60  '2020/12/12'    100       120     250.7
19        60  '2020/12/12'    100       120     250.7
20        60      20201226    100       120     250.0
21        60  '2020/12/31'     92       115     243.0
22        60  '2020/12/27'     92       118     241.0
23        60  '2020/12/16'     98       120     215.2
24        60  '2020/12/28'    103       132       NaN
25        45  '2020/12/05'    117       148     406.0
26        45  '2020/12/04'    109       175     282.4
27        45           NaN    100       119     282.0
28        45  '2020/12/24'    105       132     246.0
29        45  '2020/12/20'     97       125     243.0
30        45  '2020/12/18'     90       112       NaN
31        30  '2020/12/09'    109       133     195.1

In [ ]:
# Head and tail
# df.head(3)
# df.tail(5)

    Duration          Date  Pulse  Maxpulse  Calories
27        60  '2020/12/27'     92       118     241.0
28        60  '2020/12/28'    103       132       NaN
29        60  '2020/12/29'    100       132     280.0
30        60  '2020/12/30'    102       129     380.3
31        60  '2020/12/31'     92       115     243.0

In [ ]:
df.dropna(axis=0, how='any', inplace=True)
df

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
2         60  '2020/12/03'    103       135     340.0
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       136     374.0
7        450  '2020/12/08'    104       134     253.3
8         30  '2020/12/09'    109       133     195.1
9         60  '2020/12/10'     98       124     269.0
10        60  '2020/12/11'    103       147     329.3
11        60  '2020/12/12'    100       120     250.7
12        60  '2020/12/12'    100       120     250.7
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       132     379.3
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
17        60  '2020/12/17'    100       120     300.0
19        60  '2020/12/19'    103       123     323.0
20        45  '2020/12/20'     97       125     243.0
21        60  '2020/12/21'    108       131     364.2
23        60  '2020/12/23'    130       101     300.0
24        45  '2020/12/24'    105       132     246.0
25        60  '2020/12/25'    102       126     334.5
26        60      20201226    100       120     250.0
27        60  '2020/12/27'     92       118     241.0
29        60  '2020/12/29'    100       132     280.0
30        60  '2020/12/30'    102       129     380.3
31        60  '2020/12/31'     92       115     243.0

In [ ]:
df.loc[7, 'Duration'] = 45

In [ ]:
df.loc[26, 'Date'] = "'2020/12/26'"

In [ ]:
# Removendo colunas (características)
colunas = ['Duration', 'Pulse', 'Maxpulse', 'Calories']
df = df[colunas]
df

    Duration  Pulse  Maxpulse  Calories
0         60    110       130     409.1
1         60    117       145     479.0
2         60    103       135     340.0
3         45    109       175     282.4
4         45    117       148     406.0
5         60    102       127     300.0
6         60    110       136     374.0
7         45    104       134     253.3
8         30    109       133     195.1
9         60     98       124     269.0
10        60    103       147     329.3
11        60    100       120     250.7
12        60    100       120     250.7
13        60    106       128     345.3
14        60    104       132     379.3
15        60     98       123     275.0
16        60     98       120     215.2
17        60    100       120     300.0
19        60    103       123     323.0
20        45     97       125     243.0
21        60    108       131     364.2
23        60    130       101     300.0
24        45    105       132     246.0
25        60    102       126     334.5
26        60    100       120     250.0
27        60     92       118     241.0
29        60    100       132     280.0
30        60    102       129     380.3
31        60     92       115     243.0

In [ ]:
# Correlação de variáveis (características)
df.corr()

          Duration     Pulse  Maxpulse  Calories
Duration  1.000000 -0.191037 -0.398850  0.330900
Pulse    -0.191037  1.000000  0.211055  0.510361
Maxpulse -0.398850  0.211055  1.000000  0.352529
Calories  0.330900  0.510361  0.352529  1.000000

In [ ]:
# Shape (linhas, colunas)
df.shape

(29, 4)

In [ ]:
# Columns (colunas)
df.columns

Index(['Duration', 'Pulse', 'Maxpulse', 'Calories'], dtype='object')

In [ ]:
# Info
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Duration  32 non-null     int64
 1   Date      31 non-null     object
 2   Pulse     32 non-null     int64
 3   Maxpulse  32 non-null     int64
 4   Calories  30 non-null     float64
dtypes: float64(1), int64(3), object(1)
memory usage: 1.4+ KB

In [ ]:
# Describe
df.describe()

         Duration       Pulse    Maxpulse    Calories
count   32.000000   32.000000   32.000000   30.000000
mean    68.437500  103.500000  128.500000  304.680000
std     70.039591    7.832933   12.998759   66.003779
min     30.000000   90.000000  101.000000  195.100000
25%     60.000000  100.000000  120.000000  250.700000
50%     60.000000  102.500000  127.500000  291.200000
75%     60.000000  106.500000  132.250000  343.975000
max    450.000000  130.000000  175.000000  479.000000

In [ ]:
# Value Counts
df.value_counts()

Duration  Date          Pulse  Maxpulse  Calories
60        '2020/12/12'  100    120       250.7       2
30        '2020/12/09'  109    133       195.1       1
45        '2020/12/05'  117    148       406.0       1
          '2020/12/04'  109    175       282.4       1
          '2020/12/24'  105    132       246.0       1
60        '2020/12/01'  110    130       409.1       1
          '2020/12/02'  117    145       479.0       1
          '2020/12/03'  103    135       340.0       1
          '2020/12/06'  102    127       300.0       1
          '2020/12/07'  110    136       374.0       1
          '2020/12/10'  98     124       269.0       1
45        '2020/12/20'  97     125       243.0       1
60        '2020/12/11'  103    147       329.3       1
          '2020/12/13'  106    128       345.3       1
          '2020/12/14'  104    132       379.3       1
          '2020/12/15'  98     123       275.0       1
          '2020/12/16'  98     120       215.2       1
          '2020/12/17'  100    120       300.0       1
          '2020/12/19'  103    123       323.0       1
          '2020/12/21'  108    131       364.2       1
          '2020/12/23'  130    101       300.0       1
          '2020/12/25'  102    126       334.5       1
          '2020/12/27'  92     118       241.0       1
          '2020/12/29'  100    132       280.0       1
          '2020/12/30'  102    129       380.3       1
          '2020/12/31'  92     115       243.0       1
          20201226      100    120       250.0       1
450       '2020/12/08'  104    134       253.3       1
Name: count, dtype: int64

In [ ]:
# Medidas estatísticas
df['Calories'].mean()

np.float64(304.68)

Análise Exploratória Inicial

EDA

- Limpeza de dados
- Células vazias
- Dados em formato errado
- Dados duplicados