In [35]:
import pandas as pd

In [36]:
df = pd.read_csv('data.csv')
df

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
..        ...    ...       ...       ...
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

[169 rows x 4 columns]

In [37]:
df.sort_values(by=['Duration','Calories'],ascending=True,inplace=True)
df

     Duration  Pulse  Maxpulse  Calories
93         15     80       100      50.5
112        15    124       139     124.2
89         20     83       107      50.3
100        20     95       112      77.7
68         20    106       136     110.4
..        ...    ...       ...       ...
65        180     90       130     800.4
60        210    108       160    1376.0
109       210    137       184    1860.4
79        270    100       131    1729.0
69        300    108       143    1500.2

[169 rows x 4 columns]

In [38]:
df.head(10)
df.tail(100)

     Duration  Pulse  Maxpulse  Calories
52         60    106       130     263.0
9          60     98       124     269.0
156        60     97       131     270.4
157        60    100       120     270.4
125        60     98       122     271.0
..        ...    ...       ...       ...
65        180     90       130     800.4
60        210    108       160    1376.0
109       210    137       184    1860.4
79        270    100       131    1729.0
69        300    108       143    1500.2

[100 rows x 4 columns]

In [39]:
df.dropna(axis=0 ,how='any' ,inplace=True)
df

     Duration  Pulse  Maxpulse  Calories
93         15     80       100      50.5
112        15    124       139     124.2
89         20     83       107      50.3
100        20     95       112      77.7
68         20    106       136     110.4
..        ...    ...       ...       ...
65        180     90       130     800.4
60        210    108       160    1376.0
109       210    137       184    1860.4
79        270    100       131    1729.0
69        300    108       143    1500.2

[164 rows x 4 columns]

In [40]:
df.loc[7]['Duration'] = 25
df

<ipython-input-40-704456f7c204>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.loc[7]['Duration'] = 25

     Duration  Pulse  Maxpulse  Calories
93         15     80       100      50.5
112        15    124       139     124.2
89         20     83       107      50.3
100        20     95       112      77.7
68         20    106       136     110.4
..        ...    ...       ...       ...
65        180     90       130     800.4
60        210    108       160    1376.0
109       210    137       184    1860.4
79        270    100       131    1729.0
69        300    108       143    1500.2

[164 rows x 4 columns]

In [41]:
df

     Duration  Pulse  Maxpulse  Calories
93         15     80       100      50.5
112        15    124       139     124.2
89         20     83       107      50.3
100        20     95       112      77.7
68         20    106       136     110.4
..        ...    ...       ...       ...
65        180     90       130     800.4
60        210    108       160    1376.0
109       210    137       184    1860.4
79        270    100       131    1729.0
69        300    108       143    1500.2

[164 rows x 4 columns]

In [42]:
df.loc[2,'Duration'] = 45
df

     Duration  Pulse  Maxpulse  Calories
93         15     80       100      50.5
112        15    124       139     124.2
89         20     83       107      50.3
100        20     95       112      77.7
68         20    106       136     110.4
..        ...    ...       ...       ...
65        180     90       130     800.4
60        210    108       160    1376.0
109       210    137       184    1860.4
79        270    100       131    1729.0
69        300    108       143    1500.2

[164 rows x 4 columns]

In [43]:
df.drop_duplicates(inplace=True)
df

     Duration  Pulse  Maxpulse  Calories
93         15     80       100      50.5
112        15    124       139     124.2
89         20     83       107      50.3
100        20     95       112      77.7
68         20    106       136     110.4
..        ...    ...       ...       ...
65        180     90       130     800.4
60        210    108       160    1376.0
109       210    137       184    1860.4
79        270    100       131    1729.0
69        300    108       143    1500.2

[157 rows x 4 columns]

In [44]:
df.columns

Index(['Duration', 'Pulse', 'Maxpulse', 'Calories'], dtype='object')

In [45]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 157 entries, 93 to 69
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Duration  157 non-null    int64
 1   Pulse     157 non-null    int64
 2   Maxpulse  157 non-null    int64
 3   Calories  157 non-null    float64
dtypes: float64(1), int64(3)
memory usage: 6.1 KB

In [46]:
df.describe()

         Duration       Pulse    Maxpulse     Calories
count  157.000000  157.000000  157.000000   157.000000
mean    64.426752  107.942675  134.509554   379.414650
std     43.805251   14.845029   16.607311   271.342426
min     15.000000   80.000000  100.000000    50.300000
25%     45.000000  100.000000  124.000000   251.000000
50%     60.000000  106.000000  131.000000   320.400000
75%     60.000000  112.000000  143.000000   390.000000
max    300.000000  159.000000  184.000000  1860.400000

In [47]:
df.value_counts()

Duration  Pulse  Maxpulse  Calories
15        80     100       50.5        1
          124    139       124.2       1
20        83     107       50.3        1
          95     112       77.7        1
          106    136       110.4       1
                                      ..
180       101    127       600.1       1
210       108    160       1376.0      1
          137    184       1860.4      1
270       100    131       1729.0      1
300       108    143       1500.2      1
Name: count, Length: 157, dtype: int64

In [48]:
df['Calories'].median()

320.4